NAME_DISPLAY_MAP = {
    "vt_symbol": "本地代码",
    "direction": "方向",
    "gateway_name": "交易账号",
    "price": "价格",
    "volume": "数量",
    "time": "执行时间（秒）",
    "interval": "每轮间隔（秒）",
    "offset": "开平",
    "active": "算法状态",
    "traded": "成交数量",
    "order_volume": "单笔委托",
    "timer_count": "本轮读秒",
    "total_count": "累计读秒",
    "template_name": "算法模板",
    "display_volume": "挂出数量",
    "str_vt_symbol_list": "代码列表",
    "str_price_list": "价格列表",
    "str_volume_list": "数量列表",
    "algo_name": "任务名称",
}
